/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressesTab: typeof import('./components/client/user/AddressesTab.vue')['default']
    AuthDialog: typeof import('./components/client/AuthDialog.vue')['default']
    ConfirmDeleteDialog: typeof import('./components/client/ConfirmDeleteDialog.vue')['default']
    DeleteConfirmDialog: typeof import('./components/admin/DeleteConfirmDialog.vue')['default']
    FavoritesTab: typeof import('./components/client/user/FavoritesTab.vue')['default']
    FeaturedEditDialog: typeof import('./components/admin/FeaturedEditDialog.vue')['default']
    FeaturedProducts: typeof import('./components/client/FeaturedProducts.vue')['default']
    Footer: typeof import('./components/client/Footer.vue')['default']
    Header: typeof import('./components/client/Header.vue')['default']
    HeroSection: typeof import('./components/client/HeroSection.vue')['default']
    ImageUploadDialog: typeof import('./components/admin/ImageUploadDialog.vue')['default']
    Notification: typeof import('./components/common/Notification.vue')['default']
    OrdersTab: typeof import('./components/client/user/OrdersTab.vue')['default']
    ProductCategories: typeof import('./components/client/ProductCategories.vue')['default']
    ProfileTab: typeof import('./components/client/user/ProfileTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecEditDialog: typeof import('./components/admin/SpecEditDialog.vue')['default']
  }
}
