/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/admin/AdminLayout.vue')['default']
    ECommerceFooter: typeof import('./components/client/ECommerceFooter.vue')['default']
    ECommerceHeader: typeof import('./components/client/ECommerceHeader.vue')['default']
    FeaturedProducts: typeof import('./components/client/FeaturedProducts.vue')['default']
    HeroSection: typeof import('./components/client/HeroSection.vue')['default']
    Notification: typeof import('./components/common/Notification.vue')['default']
    ProductCategories: typeof import('./components/client/ProductCategories.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
