/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ECommerceFooter: typeof import('./components/ECommerceFooter.vue')['default']
    ECommerceHeader: typeof import('./components/ECommerceHeader.vue')['default']
    FeaturedProducts: typeof import('./components/FeaturedProducts.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    ProductCategories: typeof import('./components/ProductCategories.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
