/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/content/carousel': RouteRecordInfo<'/admin/content/carousel', '/admin/content/carousel', Record<never, never>, Record<never, never>>,
    '/admin/content/product': RouteRecordInfo<'/admin/content/product', '/admin/content/product', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/client/OrderPayment': RouteRecordInfo<'/client/OrderPayment', '/client/OrderPayment', Record<never, never>, Record<never, never>>,
    '/client/OrderSubmit': RouteRecordInfo<'/client/OrderSubmit', '/client/OrderSubmit', Record<never, never>, Record<never, never>>,
    '/client/ProductsDetail': RouteRecordInfo<'/client/ProductsDetail', '/client/ProductsDetail', Record<never, never>, Record<never, never>>,
    '/client/Search': RouteRecordInfo<'/client/Search', '/client/Search', Record<never, never>, Record<never, never>>,
    '/client/UserCenter': RouteRecordInfo<'/client/UserCenter', '/client/UserCenter', Record<never, never>, Record<never, never>>,
  }
}
